export {default as Login} from "./login"
export {default as Pagum} from "./pagum"
export {default as Pagdois} from "./pagdois"
export {default as Pagtres} from "./pagtres"
export {default as Pagquatro} from "./pagquatro"